/*
 *  Multi2Sim
 *  Copyright (C) 2011  Rafael Ubal (ubal@ece.neu.edu)
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

#include <unistd.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>

#include <m2s-opengl.h>


/* Error messages */

char *err_evg_opencl_note =
	"\tThis error message is generated by the Multi2Sim OpenGL library linked with\n"
	"\tyour OpenGL host application.\n"
	"\tThis implementation only provides a subset of the OpenGL specification. Please\n"
	"\temail 'development@multi2sim.org' for further support.\n";

char *err_evg_opencl_param_note =
	"\tThis error message is generated by the Multi2Sim OpenGL library linked with\n"
	"\tyour OpenGL host application. While a complete OpenGL implementation would\n"
	"\treturn an error code to your application, the Multi2Sim OpenGL library\n"
	"\twill make your program fail with an error code.\n";
