/*
 *  Multi2Sim
 *  Copyright (C) 2011  Rafael Ubal (ubal@ece.neu.edu)
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

#include <fermi-emu.h>
#include <mem-system.h>
#include <x86-emu.h>

#include <time.h>
#include <debug.h>


static char *err_frm_cuda_code =
	"\tAn invalid function code was generated by your application in a CUDA system\n"
	"\tcall. Probably, this means that your application is using an incompatible\n"
	"\tversion of the Multi2Sim CUDA driver library ('libm2s-cuda'). Please\n"
	"\trecompile your application and try again.\n";



/*
 * CUDA Driver API Implementation
 */

/* Debug */
int x86_cuda_debug_category;

/* List of CUDA driver calls */
enum frm_cuda_call_t
{
	frm_cuda_call_invalid = 0,
#define FRM_CUDA_DEFINE_CALL(name, code) frm_cuda_call_##name = code,
#include "cuda.dat"
#undef FRM_CUDA_DEFINE_CALL
	frm_cuda_call_count
};

/* List of CUDA driver call names */
char *frm_cuda_call_name[frm_cuda_call_count + 1] =
{
	NULL,
#define FRM_CUDA_DEFINE_CALL(name, code) #name,
#include "cuda.dat"
#undef FRM_CUDA_DEFINE_CALL
	NULL
};


/* Forward declarations of CUDA driver functions */
#define FRM_CUDA_DEFINE_CALL(name, code) static int frm_cuda_func_##name(void);
#include "cuda.dat"
#undef FRM_CUDA_DEFINE_CALL


/* List of CUDA driver functions */
typedef int (*frm_cuda_func_t)(void);
static frm_cuda_func_t frm_cuda_func_table[frm_cuda_call_count + 1] =
{
	NULL,
#define FRM_CUDA_DEFINE_CALL(name, code) frm_cuda_func_##name,
#include "cuda.dat"
#undef FRM_CUDA_DEFINE_CALL
	NULL
};



/*
 * CUDA global functions
 */

//void frm_cuda_init(void)
//{
//	int argc;
//	char *argv[1];
//
//	/* Initialize CUDA global mutex */
//	pthread_mutex_init(&frm_cuda_mutex, NULL);
//
//	/* Frame buffer */
//	frm_cuda_frame_buffer_init();
//
//	/* List of events */
//	frm_cuda_event_list = linked_list_create();
//
//	/* Host CUDA initialization */
//	argc = 0;
//	argv[0] = "m2s";
//	cuInit(&argc, argv);
//}
//
//
//void frm_cuda_done(void)
//{
//	struct frm_cuda_event_t *event;
//
//	/* Kill CUDA thread */
//	if (frm_cuda_thread)
//		
//
//	/* Free list of events */
//	LINKED_LIST_FOR_EACH(frm_cuda_event_list)
//	{
//		event = linked_list_get(frm_cuda_event_list);
//		frm_cuda_event_free(event);
//	}
//	linked_list_free(frm_cuda_event_list);
//
//	/* Free frame buffer */
//	frm_cuda_frame_buffer_done();
//}


int frm_cuda_call(void)
{
	int code;
	int ret;

	/* Function code */
	code = x86_isa_regs->ebx;
	if (code <= frm_cuda_call_invalid || code >= frm_cuda_call_count)
		fatal("%s: invalid CUDA function (code %d).\n%s",
			__FUNCTION__, code, err_frm_cuda_code);

	/* Debug */
	x86_cuda_debug(x86_cuda_debug_category, "CUDA call '%s' (code %d)\n",
		frm_cuda_call_name[code], code);

	/* Call CUDA function */
	assert(frm_cuda_func_table[code]);
	ret = frm_cuda_func_table[code]();

	/* Return value */
	return ret;
}



/*
 * CUDA call #1 - version
 *
 * @param struct x86_glut_version_t *version;
 *	Structure where the version of the GLUT runtime implementation will be
 *	dumped. To succeed, the major version should match in the runtime
 *	library (guest) and runtime implementation (host), whereas the minor
 *	version should be equal or higher in the implementation (host).
 *
 *	Features should be added to the GLUT runtime (guest and host) using the
 *	following rules:
 *	1)  If the guest library requires a new feature from the host
 *	    implementation, the feature is added to the host, and the minor
 *	    version is updated to the current Multi2Sim SVN revision both in
 *	    host and guest.
 *          All previous services provided by the host should remain available
 *          and backward-compatible. Executing a newer library on the older
 *          simulator will fail, but an older library on the newer simulator
 *          will succeed.
 *      2)  If a new feature is added that affects older services of the host
 *          implementation breaking backward compatibility, the major version is
 *          increased by 1 in the host and guest code.
 *          Executing a library with a different (lower or higher) major version
 *          than the host implementation will fail.
 *
 * @return
 *	The runtime implementation version is return in argument 'version'.
 *	The return value is always 0.
 */

#define FRM_CUDA_VERSION_MAJOR	1
#define FRM_CUDA_VERSION_MINOR	700

struct frm_cuda_version_t
{
	int major;
	int minor;
};

static int frm_cuda_func_version(void)
{
	unsigned int version_ptr;

	struct frm_cuda_version_t version;

	/* Arguments */
	version_ptr = x86_isa_regs->ecx;
	x86_cuda_debug(x86_cuda_debug_category, "\tversion_ptr=0x%x\n", version_ptr);

	/* Return version */
	assert(sizeof(struct frm_cuda_version_t) == 8);
	version.major = FRM_CUDA_VERSION_MAJOR;
	version.minor = FRM_CUDA_VERSION_MINOR;
	mem_write(x86_isa_mem, version_ptr, sizeof version, &version);
	x86_cuda_debug(x86_cuda_debug_category, "\tCUDA host implementation v. %d.%d\n", version.major, version.minor);

	/* Return success */
	return 0;
}




/*
 * CUDA call #2 - cuInit
 *
 * The function returns the next available GLUT event.
 *
 * @param struct x86_glut_event_t *event
 *	Pointer to a GLUT event structure where the next available event is
 *	written. If there is no new event, an event of type
 *	'x86_glut_event_idle' is returned.
 *
 * @return
 *	The return value is always 0.
 */

static int frm_cuda_func_cuInit(void)
{
	return 0;
}



/*
 * CUDA call #3 - cuDeviceGetCount
 *
 * @param char *title
 *	Title of the window.
 * @param struct x86_glut_window_properties_t *properties
 *	Pointer to a structure describing the window to be created.
 *
 * @return
 *	The host ID of the window, as returned by the GLUT host call.
 */

static int frm_cuda_func_cuDeviceGetCount(void)
{
	return 0;
}

