/*
 *  Multi2Sim
 *  Copyright (C) 2013  Rafael Ubal (ubal@ece.neu.edu)
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

#ifndef DRIVER_OPENGL_SI_SPI_H
#define DRIVER_OPENGL_SI_SPI_H

#include <memory>
#include <vector>

namespace Driver
{
	class OpenGLSIDriver;
}  // namespace Driver

namespace SI
{


// Forward declaration
class NDRange;
class PixelInfo;
class ShaderExport;
class ViewPort;
class DepthBuffer;

// Pixels(WorkItems) created for Pixel Shader need to load their barycentric 
// coordinate into VGPRs, which will work together with data in LDS(color...)
class DataForVGPRs
{
	// Window Space Coordinate
	int x;
	int y;

	// Barycentric Coordinate
	float i;
	float j;

public:
	DataForVGPRs(int x, int y, float i, float j) :
		x(x), y(y), i(i), j(j) { };

	DataForVGPRs(const PixelInfo *pixel_info);
};

// Data load to LDS
class DataForLDS
{
	std::unique_ptr<char []> lds;

public:
	DataForLDS(const char *buffer, unsigned size);
};

class DataForPixelShader
{
	// Identifier is the same as associated NDRange
	unsigned id;

	// Contain data to initialize VGPRs
	std::vector<std::unique_ptr<DataForVGPRs>> vgpr_init_data;

	// Contain data to initialize LDS
	std::unique_ptr<DataForLDS> lds_init_data;

public:
	DataForPixelShader(unsigned id) : id(id) { };

	/// Getters
	///
	/// Get id
	unsigned getId() const { return id; }

	/// Get count of vgpr_init_data
	unsigned getCount() const { return vgpr_init_data.size(); }

	/// Check if data is ready for NDRange, 1 per workitem
	/// \param workitem_count Count of workitems in NDRanges
	bool isReady(unsigned workitem_count) const {
		if (vgpr_init_data.size() == workitem_count && lds_init_data)
			return true;
		else
			return false;
	}

	/// Setters
	///
	/// Set data for LDS
	///
	/// \param buffer Buffer contains LDS data such as color, normal
	/// \param size Size of buffer
	void setLDS(const char *buffer, unsigned size);

	/// Receive/Push data for VGPRs
	///
	/// \param pixel_info Pixel information generated by scan converter
	void setVGPRs(const PixelInfo *pixel_info);

	/// Receive/Push data for VGPRs
	///
	/// \param x X position in window coordinate
	/// \param y Y position in window coordinate
	/// \param i I in barycentric coordinate
	/// \param j J in barycentric coordinate
	void setVGPRs(int x, int y, float i, float j);

};

// Shader Processor Interpolator
class SPI
{
	// Unique instance of SPI
	static std::unique_ptr<SPI> instance;

	// Private constructor. The only possible instance of the SPI
	// can be obtained with a call to getInstance()
	SPI();

	// Repository contains initialization data for Pixel Shader
	// IDs of initialization data object must match NDRange ID()
	std::vector<std::unique_ptr<DataForPixelShader>> init_data_repo;

	// Viewport to be applied to vertex export data
	std::unique_ptr<ViewPort> viewport;

	// Depth Buffer
	std::unique_ptr<DepthBuffer> depth_buffer;
	// FIXME: make it a part of global memory
	// unsigned depth_buffer_ptr // depth buffer is a part of global memory
	// unsigned depth_buffer_size

	/// Move initialization data to NDRange(created for Pixel Shader)
	void InitDataToNDRange(NDRange *ndrange);

public:

	/// Get the only instance of the SPI module. If the instance does not
	/// exist yet, it will be created, and will remain allocated until the
	/// end of the execution.
	static SPI *getInstance();

	/// Setters
	///
	/// Set viewport parameters
	void setViewport(int x, int y, int width, int height);
	
	/// Take data from export module and generate NDRange for Pixel Shader
	void genNDRange(ShaderExport *sx);
};

} // namespace SI

#endif
