/*
 *  Multi2Sim
 *  Copyright (C) 2011  Rafael Ubal (ubal@ece.neu.edu)
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

#include <x86-emu.h>

static char *x86_clrt_err_call =
	"\tAn invalid function code was generated by the your application as an\n"
	"\targument of a system call reserved for the Multi2Sim OpenCL Runtime\n"
	"\tlibrary. Please recompile your application and try again.\n";


/* List of OpenCL Runtime calls */
enum x86_clrt_call_t
{
	x86_clrt_call_invalid = 0,
#define X86_CLRT_DEFINE_CALL(name, code) x86_clrt_call_##name = code,
#include "clrt.dat"
#undef X86_CLRT_DEFINE_CALL
	x86_clrt_call_count
};


/* List of OpenCL Runtime call names */
char *x86_clrt_call_name[x86_clrt_call_count + 1] =
{
	NULL,
#define X86_CLRT_DEFINE_CALL(name, code) #name,
#include "clrt.dat"
#undef X86_CLRT_DEFINE_CALL
	NULL
};


/* Forward declarations of OpenCL Runtime functions */
#define X86_CLRT_DEFINE_CALL(name, code) static int x86_clrt_func_##name(void);
#include "clrt.dat"
#undef X86_CLRT_DEFINE_CALL


/* List of OpenCL Runtime functions */
typedef int (*x86_clrt_func_t)(void);
static x86_clrt_func_t x86_clrt_func_table[x86_clrt_call_count + 1] =
{
	NULL,
#define X86_CLRT_DEFINE_CALL(name, code) x86_clrt_func_##name,
#include "clrt.dat"
#undef X86_CLRT_DEFINE_CALL
	NULL
};


/* Debug */
int x86_clrt_debug_category;



int x86_clrt_call(void)
{
	/* Variables */
	int code;
	int ret;

	/* Function code */
	code = x86_isa_regs->ebx;
	if (code <= x86_clrt_call_invalid || code >= x86_clrt_call_count)
		fatal("%s: invalid OpenCL Runtime call (code %d).\n%s",
			__FUNCTION__, code, x86_clrt_err_call);

	/* Debug */
	x86_clrt_debug("OpenCL Runtime call '%s' (code %d)\n",
		x86_clrt_call_name[code], code);

	/* Call OpenCL Runtime function */
	assert(x86_clrt_func_table[code]);
	ret = x86_clrt_func_table[code]();

	/* Return value */
	return ret;
}




/*
 * OpenCL Runtime call #1 - init
 *
 * @return
 *	The function always returns 0
 */

static int x86_clrt_func_init(void)
{
	/* Return success */
	return 0;
}

